### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by gabrielgene** [matheusgene/siteChampeaoLol#1]
Arrumar formatação do código, instala o plugin no vscode do prettier, ele vai formatar seu código toda vez que vc salvar. O vscode tem uma loja que vc consegue instalar as coisas nele https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode, e essa é a pagina do prettier pra vc ver como ele funciona https://prettier.io/ e quais linguagens ele corrige.

**Comment by matheusgene** [comment]
Esse plugin prettier é uma extensão do vscode?, porque eu já tenho ele instalado, mas não formata o código quando eu salvo.

**Comment by gabrielgene** [comment]
Então não ta configurado direito, pesquisa como configurar ele

**Comment by matheusgene** [comment]
configurei ele, agora está funcionando

**Comment by matheusgene** [comment]
Fechando essa issue por que já foi resolvido nesse commit "https://github.com/matheusgene/siteChampeaoLol/commit/d922471489b987fcd302f7f460c1ba80bdd37cb6"
