### ISSUE TITLE
Gerenciamento do projeto

### ISSUE THREAD

**Issue by gabrielgene** [matheusgene/siteChampeaoLol#3]
Olhei seu notion e não vi uma organização do que foi feito e do que precisar ser feito, como um progresso do projeto e quais são os proximos passos, esse tipo de organização é relevante pra vc treinar a habilidade de organização.

Isso inclui a funcionalidade de filtro por nome, e filtro por tipo do campeão e ainda falta a parte de carregar todos os herois da API, mas ai acho q é meio q a etapa final

**Comment by matheusgene** [comment]
atualizei hj, veja o que está faltando

**Comment by gabrielgene** [comment]
Está tudo certo, pode fechar a issue.

**Comment by matheusgene** [comment]
Fechando essa issue por que já foi atualizado o notion."https://www.notion.so/Projeto-lol-e7f5d181917d448e974c0fe4290615dd"
